VIRTUALENV := venv

virtualenv:
	@if [ -d $(VIRTUALENV) ]; then rm -rf $(VIRTUALENV); fi
	@mkdir $(VIRTUALENV)
	python -m venv $(VIRTUALENV)
	$(VIRTUALENV)/bin/python -m pip install --upgrade pip
	$(VIRTUALENV)/bin/python -m pip install -r requirements.txt

update-requirements-txt: VIRTUALENV := /tmp/venv
update-requirements-txt: 
	@if [ -d $(VIRTUALENV) ]; then rm -rf $(VIRTUALENV); fi
	@mkdir $(VIRTUALENV)
	python -m venv $(VIRTUALENV)
	$(VIRTUALENV)/bin/python -m pip install --upgrade pip
	$(VIRTUALENV)/bin/python -m pip install -r unpinned_requirements.txt
	echo "# Do not remove! Auto generated by make update-requirements-txt" > requirements.txt
	$(VIRTUALENV)/bin/pip freeze | grep -v "pkg_resources" >> requirements.txt 
